### PR TITLE
Kiosk branding changes

### LINKED ISSUE #33: change kiosk shell greeting
Change ASCII characters comprising deepcell logo.

Also, change intro text to
"
Welcome to the Deepcell Kiosk!

This Kiosk was developed by the Van Valen Lab at the California Institute of Technology.

https://vanvalenlab.caltech.edu
"

### PR DESCRIPTION
**Pull request by dylanbannon**
I 
1) changed the greeting text
and
2) changed the font of the colorful ASCII graphic at the top of the shell inside the kiosk menu.

Changing the greeting text was simple.

However, changing the ASCII characters in the Deepcell logo that displays when one drops to the shell turned into an interesting quest. The program that handles the logo display is called `figurine`. Figurine has a lot of different ASCII fonts to choose form, and those are what control which characters are used. To generate a really cool display of all possible Deepcell logos, drop to the shell inside a kiosk and execute the following:
```
export FONT_LIST=$(figurine -l)
IFS=$'\n' read -r -d '' -a FONT_LIST_ARRAY <<< "$FONT_LIST"
for i in "${FONT_LIST_ARRAY[@]}"; do echo " "; echo $i; figurine -f "$i" Deepcell; echo " "; done
```

So many cool fonts, including:
`Tiles.flf`
`Speed.flf`
`Larry 3D.flf`
`Electronic.flf`
`Def Leppard.flf`
`Dos Rebel.flf`
`Cyberlarge.flf`
`3D.flf`

For my part, I'm going to pick `Electronic.flf`, but I'd like both @willgraf and @vanvalen to review this pull request, so we can be sure we end up with the absolute coolest font possible.

Fixes #33.

Also, @osterman I couldn't find any documentation for `figurine` online. Does the project have a homepage, or does it just mysteriously get distributed with Alpine?

### CODE REVIEW

**Comment by willgraf** [comment]
[I found a website with examples of each font](http://inteist.com/figlet-font-gallery/)

I like all of the following (in no particular order):

```
Electronic.flf
Larry 3D.flf
Dos Rebel.flf
Star Wars.flf
big.flf
crawford.flf
doom.flf
rounded.flf
```

They all look pretty awesome in my opinion.

**Comment by willgraf** [comment]
WOW that's a lot of cool ones.  @dylanbannon and I looked through these and found this list:

```
ANSI Regular.flf
Broadway.flf
big.flf
Electronic.flf
Georgi16.flf
Larry 3D 2.flf
Small.flf
Speed.flf
Star Wars.flf

**Comment by dylanbannon** [comment]
Per @vanvalen, @willgraf, @MekWarrior, and @dylanbannon, we're going with `Larry 3d 2.flf`

**Comment by dylanbannon** [comment]
Font set. When the logo prints, it's entirely in lowercase. Any objections to that?

**Comment by willgraf** [comment]
screen shot 2018-11-20 at 11 09 44 am
Lowercase looks fine to me.
The original  message was all lowercase as well.

**Pull request merged**
